// import type { Metadata } from "next";
"use client";
import { Geist, Geist_Mono } from "next/font/google";
import "./styles/globals.css";

import Header from "./components/layout/Header";
import Footer from "./components/layout/Footer";
import Banner from "./components/layout/Banner";
import { createContext, useEffect, useState } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// CONTEXT DARK MODE
import type { Dispatch, SetStateAction } from "react";
type DarkModeContextType = {
  dark: boolean;
  setDark: Dispatch<SetStateAction<boolean>>;
};
export const DarkModeContext = createContext<DarkModeContextType>({
  dark: false,
  setDark: () => {},
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [dark, setDark] = useState(false);

  // Hydrate dark mode from localStorage
  useEffect(() => {
    if (typeof window !== "undefined") {
      const saved = localStorage.getItem("theme");
      if (saved === "dark") {
        // Utiliser une micro-tâche pour éviter le warning React
        Promise.resolve().then(() => setDark(true));
      }
    }
  }, []);

  useEffect(() => {
    if (dark) {
      document.documentElement.classList.add("dark");
      localStorage.setItem("theme", "dark");
    } else {
      document.documentElement.classList.remove("dark");
      localStorage.setItem("theme", "light");
    }
  }, [dark]);

  return (
    <html lang="en" className={dark ? "dark" : ""}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-500 dark:bg-gray-950 dark:text-white`}
      >
        <DarkModeContext.Provider value={{ dark, setDark }}>
          <Header />
          <Banner />
          <main className="">{children}</main>
          <Footer />
        </DarkModeContext.Provider>
      </body>
    </html>
  );
}
